//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhereIsMakkah.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WhereIsMakkah.Lang.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where Is Makkah shows the direction to Makkah (Mecca.).
        /// </summary>
        public static string AboutLabel {
            get {
                return ResourceManager.GetString("AboutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2011 Ron Huang. All rights reserved.  Use of this source code is governed by a BSD-style license that can be found in the LICENSE file..
        /// </summary>
        public static string AppCopyrightText {
            get {
                return ResourceManager.GetString("AppCopyrightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ApplicationBarSettingsLabel {
            get {
                return ResourceManager.GetString("ApplicationBarSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where Is Makkah.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wikimedia Commons/Bluemangoa2z.
        /// </summary>
        public static string BackgroundCopyrightText {
            get {
                return ResourceManager.GetString("BackgroundCopyrightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string BackgroundLabel {
            get {
                return ResourceManager.GetString("BackgroundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makkah is approximately {0} {1} away..
        /// </summary>
        public static string DistanceLabel {
            get {
                return ResourceManager.GetString("DistanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click the ad if you like this application..
        /// </summary>
        public static string DonateLabel {
            get {
                return ResourceManager.GetString("DonateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion is not supported on this device..
        /// </summary>
        public static string FeedbackMotionNotSupportedLabel {
            get {
                return ResourceManager.GetString("FeedbackMotionNotSupportedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion is unable to start..
        /// </summary>
        public static string FeedbackMotionUnableToStartLabel {
            get {
                return ResourceManager.GetString("FeedbackMotionUnableToStartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application does not have permission to access location service..
        /// </summary>
        public static string FeedbackNoAccessLabel {
            get {
                return ResourceManager.GetString("FeedbackNoAccessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location service is not functioning on this device..
        /// </summary>
        public static string FeedbackNoFunctionLabel {
            get {
                return ResourceManager.GetString("FeedbackNoFunctionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location data is not available..
        /// </summary>
        public static string FeedbackNotAvailableLabel {
            get {
                return ResourceManager.GetString("FeedbackNotAvailableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow is pointing toward Makkah..
        /// </summary>
        public static string FeedbackReadyLabel {
            get {
                return ResourceManager.GetString("FeedbackReadyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting location service. This may take a while..
        /// </summary>
        public static string FeedbackStartingLabel {
            get {
                return ResourceManager.GetString("FeedbackStartingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wikimedia Commons/Basil D Soufi.
        /// </summary>
        public static string IconCopyrightText {
            get {
                return ResourceManager.GetString("IconCopyrightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string IconLabel {
            get {
                return ResourceManager.GetString("IconLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imperial (miles).
        /// </summary>
        public static string ImperialLabel {
            get {
                return ResourceManager.GetString("ImperialLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mile(s).
        /// </summary>
        public static string ImperialUnitLabel {
            get {
                return ResourceManager.GetString("ImperialUnitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string LicenseLabel {
            get {
                return ResourceManager.GetString("LicenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application requires location service to determine your current position. We do not store your position..
        /// </summary>
        public static string LocationServiceDisclosureLabel {
            get {
                return ResourceManager.GetString("LocationServiceDisclosureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Service.
        /// </summary>
        public static string LocationServiceLabel {
            get {
                return ResourceManager.GetString("LocationServiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric (kilometers).
        /// </summary>
        public static string MetricLabel {
            get {
                return ResourceManager.GetString("MetricLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilometer(s).
        /// </summary>
        public static string MetricUnitLabel {
            get {
                return ResourceManager.GetString("MetricUnitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: with Windows Phone 7.5, you no longer have to manually point the top of the phone toward north first to show the direction to Makkah..
        /// </summary>
        public static string NoteLabel {
            get {
                return ResourceManager.GetString("NoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where Is Makkah.
        /// </summary>
        public static string TitleLabel {
            get {
                return ResourceManager.GetString("TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string UnitLabel {
            get {
                return ResourceManager.GetString("UnitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        public static string VersionLabel {
            get {
                return ResourceManager.GetString("VersionLabel", resourceCulture);
            }
        }
    }
}
